#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := gameControl.cpp graphicalInterface.cpp icon.cpp

# header files in this project
HEADERS := gameControl.hpp graphicalInterface.hpp icon.hpp 

# other places to look for files for this project
SEARCH  := sources headers assets

# set REATIVE to the next higher directory 
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.native